# Generated by Django 4.2.23 on 2025-06-16 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopiaDeLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado'), ('manutencao', 'Em manutenção')], default='disponivel', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('id_membro', models.CharField(max_length=10, unique=True)),
                ('contato', models.CharField(max_length=100)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.enderecomembro')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autores', models.CharField(max_length=200)),
                ('isbn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.isbn')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao_real', models.DateField(blank=True, null=True)),
                ('copia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.copiadelivro')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.membro')),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.periodoemprestimo')),
            ],
        ),
        migrations.AddField(
            model_name='copiadelivro',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.livro'),
        ),
    ]
