# Generated by Django 4.2.23 on 2025-06-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='numero_copias',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
