# Generated by Django 4.2.23 on 2025-06-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livro_numero_copias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='id_membro',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
