# Generated by Django 4.2.23 on 2025-06-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_membro_id_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.enderecomembro'),
        ),
    ]
