# Generated by Django 4.2.23 on 2025-06-16 20:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membro_email_alter_membro_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=core.models.EnderecoMembro),
        ),
    ]
