# Generated by Django 4.2.23 on 2025-06-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_membro_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membro',
            old_name='id_membro',
            new_name='cpf',
        ),
        migrations.AlterField(
            model_name='membro',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
