# Generated by Django 4.2.23 on 2025-06-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_id_membro_membro_cpf_alter_membro_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
