# Generated by Django 4.2.23 on 2025-06-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_livro_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_devolucao_real',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='periodo',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
