# Generated by Django 4.2.23 on 2025-06-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_emprestimo_data_devolucao_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='periodo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.periodoemprestimo'),
            preserve_default=False,
        ),
    ]
