# Generated by Django 4.2.23 on 2025-06-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emprestimo_data_devolucao_real_emprestimo_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_emprestimo',
        ),
    ]
