# Generated by Django 4.2.23 on 2025-06-16 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao_real',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
