# Generated by Django 4.2.23 on 2025-06-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_emprestimo_data_devolucao_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(default='ativo', max_length=20),
        ),
    ]
