# Generated by Django 4.2.23 on 2025-06-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_emprestimo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='status',
        ),
    ]
